### ISSUE TITLE
Updating Pi-hole Core to 5.14.1 still shows "Red" in PADD

### ISSUE THREAD

**Issue by kagegoomba** [pi-hole/PADD#273]
Updated my Pi-hole to latest version - PADD still says its outdated - already updated twice - updated PADD - no change.
Not sure if bug or other. Everything else is fine - working great - just annoyed by the version notice.

**Comment by yubiuser** [comment]
Note: we should use the version file instead of using `pihole -v`

**Comment by yubiuser** [comment]
Ok, that's strange. I don't see it in red - but I'll prepare something anymway.

**Comment by yubiuser** [comment]
@kagegoomba 

Please check, if this version fixes the issue for you.

https://github.com/pi-hole/PADD/blob/versions_file/padd.sh

**Comment by kagegoomba** [comment]
Don't suppose you could pinpoint want lines changed - don't exactly have an easy way to drop this file on my device short of pulling a new copy off the server ( I suspect this isn't official yet)

**Comment by yubiuser** [comment]
You can see the changes here: https://github.com/pi-hole/PADD/pull/274/files

Easiest is probably to replace the whole `padd.sh` with the content from here: 
https://raw.githubusercontent.com/pi-hole/PADD/versions_file/padd.sh

**Comment by mikegee81** [comment]
Hi @yubiuser I tried the updated padd.sh at the link you provided. Pi-hole v5.14.1, Web v5.17, and FTL v5.19.1 still display in red.

**Comment by yubiuser** [comment]
What's the content of your `/etc/pihole/versions`?

**Comment by mikegee81** [comment]
`CORE_BRANCH=master
WEB_BRANCH=master
FTL_BRANCH=master
CORE_VERSION=v5.14.1
WEB_VERSION=v5.17
FTL_VERSION=v5.19.1
GITHUB_CORE_VERSION=
GITHUB_WEB_VERSION=
GITHUB_FTL_VERSION=
CORE_HASH=21026d9
GITHUB_CORE_HASH=
WEB_HASH=da2764e
GITHUB_WEB_HASH=
FTL_HASH=b48b3e1f
GITHUB_FTL_HASH=
`

**Comment by yubiuser** [comment]
It seems Pi-hole failed to get the latest version information from Github.
Please run `pihole updateckecker` and see if solved the issue.

P.S. This is not an issue with `PADD` but Pi-hole itself.

**Comment by mikegee81** [comment]
Yes, that fixed it. Thanks so much!

**Comment by kagegoomba** [comment]
No change - modded the file as you directed.
also tried pihole updatechecker after the changes.

**Comment by kagegoomba** [comment]
`CORE_BRANCH=master
WEB_BRANCH=master
FTL_BRANCH=master
CORE_VERSION=v5.14.1
WEB_VERSION=v5.17
FTL_VERSION=v5.19.1
GITHUB_CORE_VERSION=v5.14.1
GITHUB_WEB_VERSION=v5.17
GITHUB_FTL_VERSION=v5.19.1
CORE_HASH=21026d94
GITHUB_CORE_HASH=21026d9
WEB_HASH=da2764e5
GITHUB_WEB_HASH=da2764e
FTL_HASH=b48b3e1f
GITHUB_FTL_HASH=b48b3e1
`

**Comment by yubiuser** [comment]
This looks good. 

Please run `bash -x padd.sh`. This will produce **a lot** of output, you can cancel after 3 seconds. Please share the output.

**Comment by kagegoomba** [comment]
```
+ LC_ALL=C
+ LC_NUMERIC=C
+ padd_version=v3.8.1
++ date +%s
+ LastCheckVersionInformation=1668634177
++ date +%s
+ LastCheckNetworkInformation=1668634177
++ date +%s
+ LastCheckSummaryInformation=1668634177
++ date +%s
+ LastCheckPiholeInformation=1668634177
++ date +%s
+ LastCheckSystemInformation=1668634177
++ nproc --all
+ core_count=4
++ printf '\033'
+ rSI='
   ed_text=''
+ green_text=''
+ yellow_text=''
+ blue_text=''
+ magenta_text=''
+ cyan_text=''
+ reset_text=''
+ clear_line=''
+ bold_text=''
+ blinking_text=''
+ dim_text=''
+ check_box_good='[✓]'
+ check_box_bad='[✗]'
+ check_box_question='[?]'
+ check_box_info='[i]'
+ pico_status_ok='[✓] Sys. OK'
+ pico_status_update='[i] Update'
+ pico_status_hot='[✗] Sys. Hot!'
+ pico_status_off='[✗] Offline'
+ pico_status_ftl_down='[i] FTL Down'
+ pico_status_dns_down='[✗] DNS Down'
+ pico_status_unknown='[?] Stat. Unk.'
+ mini_status_ok='[✓] System OK'
+ mini_status_update='[i] Update avail.'
+ mini_status_hot='[✗] System is hot!'
+ mini_status_off='[✗] Pi-hole off!'
+ mini_status_ftl_down='[i] FTL down!'
+ mini_status_dns_down='[✗] DNS off!'
+ mini_status_unknown='[?] Status unknown'
+ full_status_ok='[✓] System is healthy.'
+ full_status_update='[i] Updates are available.'
+ full_status_hot='[✗] System is hot!'
+ full_status_off='[✗] Pi-hole is offline'
+ full_status_ftl_down='[i] FTL is down!'
+ full_status_dns_down='[✗] DNS is off!'
+ full_status_unknown='[?] Status unknown!'
+ mega_status_ok='[✓] Your system is healthy.'
+ mega_status_update='[i] Updates are available.'
++ tput cols
+ console_width=80
++ tput lines
+ console_height=24
+ SizeChecker
+ '[' 80 -lt 20 ']'
+ '[' 24 -lt 10 ']'
+ '[' 80 -lt 24 ']'
+ '[' 24 -lt 12 ']'
+ '[' 80 -lt 30 ']'
+ '[' 24 -lt 16 ']'
+ '[' 80 -lt 40 ']'
+ '[' 24 -lt 18 ']'
+ '[' 80 -lt 53 ']'
+ '[' 24 -lt 20 ']'
+ '[' 80 -lt 60 ']'
+ '[' 24 -lt 21 ']'
+ '[' 80 -lt 80 ']'
+ '[' 24 -lt 26 ']'
+ '[' 24 -lt 22 ']'
+ padd_size=regular
+ StartupRoutine regular
+ . /etc/pihole/setupVars.conf
++ BLOCKING_ENABLED=true
++ PIHOLE_DNS_3=1.1.1.1
++ PIHOLE_DNS_4=1.0.0.1
++ DNSSEC=false
++ REV_SERVER=false
++ ADMIN_EMAIL=
++ WEBUIBOXEDLAYOUT=boxed
++ WEBTHEME=default-dark
++ WEBPASSWORD=4be4722ed3bcf7a2e55aa8e6a1c0756ce3b22b1447f014d0cb314887489ae48f
++ IPV4_ADDRESS=192.168.200.200/24
++ IPV6_ADDRESS=
++ PIHOLE_INTERFACE=eth0
++ PIHOLE_DNS_1=208.67.222.222
++ PIHOLE_DNS_2=208.67.220.220
++ QUERY_LOGGING=true
++ INSTALL_WEB_SERVER=true
++ INSTALL_WEB_INTERFACE=true
++ LIGHTTPD_ENABLED=true
++ CACHE_SIZE=10000
++ DNS_FQDN_REQUIRED=true
++ DNS_BOGUS_PRIV=true
++ DNSMASQ_LISTENING=single
+ . /etc/pihole/versions
++ CORE_BRANCH=master
++ WEB_BRANCH=master
++ FTL_BRANCH=master
++ CORE_VERSION=v5.14.1
++ WEB_VERSION=v5.17
++ FTL_VERSION=v5.19.1
++ GITHUB_CORE_VERSION=v5.14.1
++ GITHUB_WEB_VERSION=v5.17
++ GITHUB_FTL_VERSION=v5.19.1
++ CORE_HASH=21026d94
++ GITHUB_CORE_HASH=21026d9
++ WEB_HASH=da2764e5
++ GITHUB_WEB_HASH=da2764e
++ FTL_HASH=b48b3e1f
++ GITHUB_FTL_HASH=b48b3e1
+ '[' regular = pico ']'
+ '[' regular = nano ']'
+ '[' regular = micro ']'
+ '[' regular = mini ']'
+ printf %b ' __      __  __   \n'
 __      __  __
+ printf %b '|__) /\ |  \|  \  Pi-hole® Ad Detection Display\n'
|__) /\ |  \|  \  Pi-hole® Ad Detection Display
+ printf %b '|   /--\|__/|__/  A client for Pi-hole\n\n'
|   /--\|__/|__/  A client for Pi-hole

+ '[' regular = tiny ']'
+ echo 'START UP ==================================================='
START UP ===================================================
+ printf %b '- Checking internet connection...\n'
- Checking internet connection...
+ CheckConnectivity regular
+ local connectivity connection_attempts wait_timer
+ connectivity=false
+ connection_attempts=1
+ wait_timer=1
+ '[' 1 -lt 9 ']'
+ nc -zw1 google.com 443
+ '[' regular = pico ']'
+ '[' regular = nano ']'
+ '[' regular = micro ']'
+ '[' regular = mini ']'
+ echo '  - Attempt 1 passed...                                     '
  - Attempt 1 passed...
+ connectivity=true
+ connection_attempts=11
+ '[' 11 -lt 9 ']'
+ '[' true = false ']'
+ '[' regular = pico ']'
+ '[' regular = nano ']'
+ '[' regular = micro ']'
+ '[' regular = mini ']'
+ '[' regular = tiny ']'
+ echo '  - Connectivity check passed...'
  - Connectivity check passed...
+ echo '- Gathering system information...'
- Gathering system information...
+ GetSystemInformation regular
+ '[' regular = pico ']'
+ '[' regular = nano ']'
+ '[' regular = micro ']'
++ uptime
++ awk '-F( |,|:)+' '{if ($7=="min") m=$6; else {if ($7~/^day/){if ($9=="min") {
d=$6;m=$8} else {d=$6;h=$8;m=$9}} else {h=$6;m=$7}}} {print d+0,"days,",h+0,"hou
rs,",m+0,"minutes"}'
+ system_uptime='0 days, 21 hours, 25 minutes'
+ '[' -f /sys/class/thermal/thermal_zone0/temp ']'
++ cat /sys/class/thermal/thermal_zone0/temp
+ cpu=40407
+ '[' '' = F ']'
+ '[' '' = K ']'
+++ echo 40407
+++ awk '{print $1 / 1000}'
++ printf %.1f 40.407
+ temperature=$'40.4\302\260C'
++ awk '{print $1}'
+ cpu_load_1=1.08
++ awk '{print $2}'
+ cpu_load_5=0.84
++ awk '{print $3}'
+ cpu_load_15=0.82
++ HeatmapGenerator 1.08 4
++ '[' -z 4 ']'
++++ echo '1.08 4'
++++ awk '{print ($1 / $2) * 100}'
+++ printf %.0f 27
++ load=27
++ '[' 27 -lt 75 ']'
++ out=''
++ echo ''
+ cpu_load_1_heatmap=''
++ HeatmapGenerator 0.84 4
++ '[' -z 4 ']'
++++ echo '0.84 4'
++++ awk '{print ($1 / $2) * 100}'
+++ printf %.0f 21
++ load=21
++ '[' 21 -lt 75 ']'
++ out=''
++ echo ''
+ cpu_load_5_heatmap=''
++ HeatmapGenerator 0.82 4
++ '[' -z 4 ']'
++++ echo '0.82 4'
++++ awk '{print ($1 / $2) * 100}'
+++ printf %.0f 20.5
++ load=20
++ '[' 20 -lt 75 ']'
++ out=''
++ echo ''
+ cpu_load_15_heatmap=''
+++ echo '1.08 4'
+++ awk '{print ($1 / $2) * 100}'
++ printf %.1f 27
+ cpu_percent=27.0
+ '[' 40407 -gt 80000 ']'
+ '[' 40407 -gt 70000 ']'
+ '[' 40407 -gt 60000 ']'
+ temp_heatmap=''
++ awk '/MemTotal:/{total=$2} /MemFree:/{free=$2} /Buffers:/{buffers=$2} /^Cache
d:/{cached=$2} END {printf "%.1f", (total-free-buffers-cached)*100/total}' /proc
/meminfo
+ memory_percent=2.2
++ HeatmapGenerator 2.2
++ '[' -z '' ']'
+++ printf %.0f 2.2
++ load=2
++ '[' 2 -lt 75 ']'
++ out=''
++ echo ''
+ memory_heatmap=''
+ '[' regular = mini ']'
+ '[' regular = tiny ']'
++ BarGenerator 27.0 10
++++ echo '27.0 10'
++++ awk '{print ($1 / 100) * $2}'
+++ printf %.f 2.7
++ barNumber=3
++++ seq 3
+++ for i in $(seq "$barNumber")
+++ printf %b $'\342\226\240'
+++ for i in $(seq "$barNumber")
+++ printf %b $'\342\226\240'
+++ for i in $(seq "$barNumber")
+++ printf %b $'\342\226\240'
++ frontFill=$'\342\226\240\342\226\240\342\226\240'
++ backfillNumber=7
++ '[' 3 -lt 10 ']'
++ '[' '' = color ']'
++++ seq 7
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\302\267'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\302\267'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\302\267'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\302\267'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\302\267'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\302\267'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\302\267'
++ backFill=$'\302\267\302\267\302\267\302\267\302\267\302\267\302\267'
++ out='■■■·······'
++ echo '■■■·······'
+ cpu_bar='■■■·······'
++ BarGenerator 2.2 10
++++ echo '2.2 10'
++++ awk '{print ($1 / 100) * $2}'
+++ printf %.f 0.22
++ barNumber=0
++++ seq 0
++ frontFill=
++ backfillNumber=10
++ '[' 0 -lt 10 ']'
++ '[' '' = color ']'
++++ seq 10
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\302\267'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\302\267'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\302\267'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\302\267'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\302\267'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\302\267'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\302\267'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\302\267'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\302\267'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\302\267'
++ backFill=$'\302\267\302\267\302\267\302\267\302\267\302\267\302\267\302\267\3
02\267\302\267'
++ out='··········'
++ echo '··········'
+ memory_bar='··········'
+ '[' -f /sys/firmware/devicetree/base/model ']'
++ tr -d '\0'
+ sys_model='Raspberry Pi 4 Model B Rev 1.4'
+ echo '- Gathering Pi-hole information...'
- Gathering Pi-hole information...
+ GetSummaryInformation regular
++ GetFTLData stats
++ local ftl_port data
+++ getFTLAPIPort
+++ local FTLCONFFILE=/etc/pihole/pihole-FTL.conf
+++ local DEFAULT_FTL_PORT=4711
+++ local ftl_api_port
+++ '[' -s /etc/pihole/pihole-FTL.conf ']'
++++ grep '^FTLPORT=' /etc/pihole/pihole-FTL.conf
++++ cut -d= -f2-
++++ echo 4711
+++ ftl_api_port=4711
+++ expr 4711 : '[^[:digit:]]'
+++ echo 4711
++ ftl_port=4711
++ '[' -n 4711 ']'
+++ echo '>stats >quit'
+++ nc 127.0.0.1 4711
++ data='domains_being_blocked 513484
dns_queries_today 84477
ads_blocked_today 1295
ads_percentage_today 1.532962
unique_domains 3768
queries_forwarded 39710
queries_cached 42792
clients_ever_seen 22
unique_clients 21
dns_queries_all_types 84477
reply_UNKNOWN 877
reply_NODATA 16848
reply_NXDOMAIN 19583
reply_CNAME 22514
reply_IP 23954
reply_DOMAIN 388
reply_RRNAME 8
reply_SERVFAIL 294
reply_REFUSED 0
reply_NOTIMP 0
reply_OTHER 0
reply_DNSSEC 0
reply_NONE 0
reply_BLOB 11
dns_queries_all_replies 84477
privacy_level 0
status enabled'
++ echo 'domains_being_blocked 513484
dns_queries_today 84477
ads_blocked_today 1295
ads_percentage_today 1.532962
unique_domains 3768
queries_forwarded 39710
queries_cached 42792
clients_ever_seen 22
unique_clients 21
dns_queries_all_types 84477
reply_UNKNOWN 877
reply_NODATA 16848
reply_NXDOMAIN 19583
reply_CNAME 22514
reply_IP 23954
reply_DOMAIN 388
reply_RRNAME 8
reply_SERVFAIL 294
reply_REFUSED 0
reply_NOTIMP 0
reply_OTHER 0
reply_DNSSEC 0
reply_NONE 0
reply_BLOB 11
dns_queries_all_replies 84477
privacy_level 0
status enabled'
+ summary='domains_being_blocked 513484
dns_queries_today 84477
ads_blocked_today 1295
ads_percentage_today 1.532962
unique_domains 3768
queries_forwarded 39710
queries_cached 42792
clients_ever_seen 22
unique_clients 21
dns_queries_all_types 84477
reply_UNKNOWN 877
reply_NODATA 16848
reply_NXDOMAIN 19583
reply_CNAME 22514
reply_IP 23954
reply_DOMAIN 388
reply_RRNAME 8
reply_SERVFAIL 294
reply_REFUSED 0
reply_NOTIMP 0
reply_OTHER 0
reply_DNSSEC 0
reply_NONE 0
reply_BLOB 11
dns_queries_all_replies 84477
privacy_level 0
status enabled'
++ GetFTLData cacheinfo
++ local ftl_port data
+++ getFTLAPIPort
+++ local FTLCONFFILE=/etc/pihole/pihole-FTL.conf
+++ local DEFAULT_FTL_PORT=4711
+++ local ftl_api_port
+++ '[' -s /etc/pihole/pihole-FTL.conf ']'
++++ grep '^FTLPORT=' /etc/pihole/pihole-FTL.conf
++++ cut -d= -f2-
++++ echo 4711
+++ ftl_api_port=4711
+++ expr 4711 : '[^[:digit:]]'
+++ echo 4711
++ ftl_port=4711
++ '[' -n 4711 ']'
+++ echo '>cacheinfo >quit'
+++ nc 127.0.0.1 4711
++ data='cache-size: 10000
cache-live-freed: 0
cache-inserted: 114226
ipv4: 240
ipv6: 27
srv: 0
cname: 135
ds: 0
dnskey: 0
other: 47
expired: 374
immortal: 15'
++ echo 'cache-size: 10000
cache-live-freed: 0
cache-inserted: 114226
ipv4: 240
ipv6: 27
srv: 0
cname: 135
ds: 0
dnskey: 0
other: 47
expired: 374
immortal: 15'
+ cache_info='cache-size: 10000
cache-live-freed: 0
cache-inserted: 114226
ipv4: 240
ipv6: 27
srv: 0
cname: 135
ds: 0
dnskey: 0
other: 47
expired: 374
immortal: 15'
++ echo 'domains_being_blocked 513484
dns_queries_today 84477
ads_blocked_today 1295
ads_percentage_today 1.532962
unique_domains 3768
queries_forwarded 39710
queries_cached 42792
clients_ever_seen 22
unique_clients 21
dns_queries_all_types 84477
reply_UNKNOWN 877
reply_NODATA 16848
reply_NXDOMAIN 19583
reply_CNAME 22514
reply_IP 23954
reply_DOMAIN 388
reply_RRNAME 8
reply_SERVFAIL 294
reply_REFUSED 0
reply_NOTIMP 0
reply_OTHER 0
reply_DNSSEC 0
reply_NONE 0
reply_BLOB 11
dns_queries_all_replies 84477
privacy_level 0
status enabled'
++ grep unique_clients
++ grep -Eo '[0-9]+$'
+ clients=21
++ echo 'domains_being_blocked 513484
dns_queries_today 84477
ads_blocked_today 1295
ads_percentage_today 1.532962
unique_domains 3768
queries_forwarded 39710
queries_cached 42792
clients_ever_seen 22
unique_clients 21
dns_queries_all_types 84477
reply_UNKNOWN 877
reply_NODATA 16848
reply_NXDOMAIN 19583
reply_CNAME 22514
reply_IP 23954
reply_DOMAIN 388
reply_RRNAME 8
reply_SERVFAIL 294
reply_REFUSED 0
reply_NOTIMP 0
reply_OTHER 0
reply_DNSSEC 0
reply_NONE 0
reply_BLOB 11
dns_queries_all_replies 84477
privacy_level 0
status enabled'
++ grep status
++ grep -Eo 'enabled|disabled|unknown'
+ blocking_status=enabled
++ echo 'domains_being_blocked 513484
dns_queries_today 84477
ads_blocked_today 1295
ads_percentage_today 1.532962
unique_domains 3768
queries_forwarded 39710
queries_cached 42792
clients_ever_seen 22
unique_clients 21
dns_queries_all_types 84477
reply_UNKNOWN 877
reply_NODATA 16848
reply_NXDOMAIN 19583
reply_CNAME 22514
reply_IP 23954
reply_DOMAIN 388
reply_RRNAME 8
reply_SERVFAIL 294
reply_REFUSED 0
reply_NOTIMP 0
reply_OTHER 0
reply_DNSSEC 0
reply_NONE 0
reply_BLOB 11
dns_queries_all_replies 84477
privacy_level 0
status enabled'
++ grep -Eo '[0-9]+$'
++ grep domains_being_blocked
+ domains_being_blocked_raw=513484
++ printf %.f 513484
+ domains_being_blocked=513484
++ echo 'domains_being_blocked 513484
dns_queries_today 84477
ads_blocked_today 1295
ads_percentage_today 1.532962
unique_domains 3768
queries_forwarded 39710
queries_cached 42792
clients_ever_seen 22
unique_clients 21
dns_queries_all_types 84477
reply_UNKNOWN 877
reply_NODATA 16848
reply_NXDOMAIN 19583
reply_CNAME 22514
reply_IP 23954
reply_DOMAIN 388
reply_RRNAME 8
reply_SERVFAIL 294
reply_REFUSED 0
reply_NOTIMP 0
reply_OTHER 0
reply_DNSSEC 0
reply_NONE 0
reply_BLOB 11
dns_queries_all_replies 84477
privacy_level 0
status enabled'
++ grep dns_queries_today
++ grep -Eo '[0-9]+$'
+ dns_queries_today_raw=84477
++ printf %.f 84477
+ dns_queries_today=84477
++ echo 'domains_being_blocked 513484
dns_queries_today 84477
ads_blocked_today 1295
ads_percentage_today 1.532962
unique_domains 3768
queries_forwarded 39710
queries_cached 42792
clients_ever_seen 22
unique_clients 21
dns_queries_all_types 84477
reply_UNKNOWN 877
reply_NODATA 16848
reply_NXDOMAIN 19583
reply_CNAME 22514
reply_IP 23954
reply_DOMAIN 388
reply_RRNAME 8
reply_SERVFAIL 294
reply_REFUSED 0
reply_NOTIMP 0
reply_OTHER 0
reply_DNSSEC 0
reply_NONE 0
reply_BLOB 11
dns_queries_all_replies 84477
privacy_level 0
status enabled'
++ grep ads_blocked_today
++ grep -Eo '[0-9]+$'
+ ads_blocked_today_raw=1295
++ printf %.f 1295
+ ads_blocked_today=1295
++ echo 'domains_being_blocked 513484
dns_queries_today 84477
ads_blocked_today 1295
ads_percentage_today 1.532962
unique_domains 3768
queries_forwarded 39710
queries_cached 42792
clients_ever_seen 22
unique_clients 21
dns_queries_all_types 84477
reply_UNKNOWN 877
reply_NODATA 16848
reply_NXDOMAIN 19583
reply_CNAME 22514
reply_IP 23954
reply_DOMAIN 388
reply_RRNAME 8
reply_SERVFAIL 294
reply_REFUSED 0
reply_NOTIMP 0
reply_OTHER 0
reply_DNSSEC 0
reply_NONE 0
reply_BLOB 11
dns_queries_all_replies 84477
privacy_level 0
status enabled'
++ grep ads_percentage_today
++ grep -Eo '[0-9.]+$'
+ ads_percentage_today_raw=1.532962
++ printf %.1f 1.532962
+ ads_percentage_today=1.5
++ echo 'cache-size: 10000
cache-live-freed: 0
cache-inserted: 114226
ipv4: 240
ipv6: 27
srv: 0
cname: 135
ds: 0
dnskey: 0
other: 47
expired: 374
++ grep cache-size
++ grep -Eo '[0-9.]+$'
immortal: 15'
+ cache_size=10000
++ echo 'cache-size: 10000
cache-live-freed: 0
cache-inserted: 114226
ipv4: 240
ipv6: 27
srv: 0
cname: 135
ds: 0
dnskey: 0
other: 47
expired: 374
immortal: 15'
++ grep cache-live-freed
++ grep -Eo '[0-9.]+$'
+ cache_deletes=0
++ echo 'cache-size: 10000
cache-live-freed: 0
cache-inserted: 114226
ipv4: 240
ipv6: 27
srv: 0
cname: 135
ds: 0
dnskey: 0
other: 47
expired: 374
immortal: 15'
++ grep cache-inserted
++ grep -Eo '[0-9.]+$'
+ cache_inserts=114226
++ GetFTLData recentBlocked
++ local ftl_port data
+++ getFTLAPIPort
+++ local FTLCONFFILE=/etc/pihole/pihole-FTL.conf
+++ local DEFAULT_FTL_PORT=4711
+++ local ftl_api_port
+++ '[' -s /etc/pihole/pihole-FTL.conf ']'
++++ grep '^FTLPORT=' /etc/pihole/pihole-FTL.conf
++++ cut -d= -f2-
++++ echo 4711
+++ ftl_api_port=4711
+++ expr 4711 : '[^[:digit:]]'
+++ echo 4711
++ ftl_port=4711
++ '[' -n 4711 ']'
+++ echo '>recentBlocked >quit'
+++ nc 127.0.0.1 4711
++ data=app-measurement.com
++ echo app-measurement.com
+ latest_blocked=app-measurement.com
++ GetFTLData 'top-ads (1)'
++ awk '{print $3}'
++ local ftl_port data
+++ getFTLAPIPort
+++ local FTLCONFFILE=/etc/pihole/pihole-FTL.conf
+++ local DEFAULT_FTL_PORT=4711
+++ local ftl_api_port
+++ '[' -s /etc/pihole/pihole-FTL.conf ']'
++++ grep '^FTLPORT=' /etc/pihole/pihole-FTL.conf
++++ cut -d= -f2-
++++ echo 4711
+++ ftl_api_port=4711
+++ expr 4711 : '[^[:digit:]]'
+++ echo 4711
++ ftl_port=4711
++ '[' -n 4711 ']'
+++ echo '>top-ads (1) >quit'
+++ nc 127.0.0.1 4711
++ data='0 429 events.launchdarkly.com'
++ echo '0 429 events.launchdarkly.com'
+ top_blocked=events.launchdarkly.com
++ GetFTLData 'top-domains (1)'
++ local ftl_port data
++ awk '{print $3}'
+++ getFTLAPIPort
+++ local FTLCONFFILE=/etc/pihole/pihole-FTL.conf
+++ local DEFAULT_FTL_PORT=4711
+++ local ftl_api_port
+++ '[' -s /etc/pihole/pihole-FTL.conf ']'
++++ grep '^FTLPORT=' /etc/pihole/pihole-FTL.conf
++++ cut -d= -f2-
++++ echo 4711
+++ ftl_api_port=4711
+++ expr 4711 : '[^[:digit:]]'
+++ echo 4711
++ ftl_port=4711
++ '[' -n 4711 ']'
+++ echo '>top-domains (1) >quit'
+++ nc 127.0.0.1 4711
++ data='0 7154 exceed-primary-production-lb.intellum.com'
++ echo '0 7154 exceed-primary-production-lb.intellum.com'
+ top_domain=exceed-primary-production-lb.intellum.com
++ GetFTLData 'top-clients (1)'
++ local ftl_port data
++ awk '{print $4}'
+++ getFTLAPIPort
+++ local FTLCONFFILE=/etc/pihole/pihole-FTL.conf
+++ local DEFAULT_FTL_PORT=4711
+++ local ftl_api_port
+++ '[' -s /etc/pihole/pihole-FTL.conf ']'
++++ grep '^FTLPORT=' /etc/pihole/pihole-FTL.conf
++++ cut -d= -f2-
++++ echo 4711
+++ ftl_api_port=4711
+++ expr 4711 : '[^[:digit:]]'
+++ echo 4711
++ ftl_port=4711
++ '[' -n 4711 ']'
+++ echo '>top-clients (1) >quit'
+++ nc 127.0.0.1 4711
++ data='0 55118 192.168.200.171 '
++ echo '0 55118 192.168.200.171 '
+ top_client_raw=
+ '[' -z '' ']'
++ GetFTLData 'top-clients (1)'
++ local ftl_port data
++ awk '{print $3}'
+++ getFTLAPIPort
+++ local FTLCONFFILE=/etc/pihole/pihole-FTL.conf
+++ local DEFAULT_FTL_PORT=4711
+++ local ftl_api_port
+++ '[' -s /etc/pihole/pihole-FTL.conf ']'
++++ grep '^FTLPORT=' /etc/pihole/pihole-FTL.conf
++++ cut -d= -f2-
++++ echo 4711
+++ ftl_api_port=4711
+++ expr 4711 : '[^[:digit:]]'
+++ echo 4711
++ ftl_port=4711
++ '[' -n 4711 ']'
+++ echo '>top-clients (1) >quit'
+++ nc 127.0.0.1 4711
++ data='0 55118 192.168.200.171 '
++ echo '0 55118 192.168.200.171 '
+ top_client=192.168.200.171
+ '[' regular = pico ']'
+ '[' regular = nano ']'
+ '[' regular = micro ']'
+ '[' regular = mini ']'
+ '[' regular = tiny ']'
+ '[' regular = regular ']'
++ BarGenerator 1.5 40 color
++++ echo '1.5 40'
++++ awk '{print ($1 / 100) * $2}'
+++ printf %.f 0.6
++ barNumber=1
++++ seq 1
+++ for i in $(seq "$barNumber")
+++ printf %b $'\342\226\240'
++ frontFill=$'\342\226\240'
++ backfillNumber=39
++ '[' 1 -lt 40 ']'
++ '[' color = color ']'
++++ seq 39
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
+++ for i in $(seq $backfillNumber)
+++ printf %b $'\342\226\240'
++ backFill=$'\342\226\240\342\226\240\342\226\240\342\226\240\342\226\240\342\2
26\240\342\226\240\342\226\240\342\226\240\342\226\240\342\226\240\342\226\240\3
42\226\240\342\226\240\342\226\240\342\226\240\342\226\240\342\226\240\342\226\2
40\342\226\240\342\226\240\342\226\240\342\226\240\342\226\240\342\226\240\342\2
26\240\342\226\240\342\226\240\342\226\240\342\226\240\342\226\240\342\226\240\3
42\226\240\342\226\240\342\226\240\342\226\240\342\226\240\342\226\240\342\226\2
40'
++ out='■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■'
++ echo '■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■'
+ ads_blocked_bar='■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■'
+ GetPiholeInformation regular
++ pidof pihole-FTL
+ ftlPID=904
+ '[' -z x ']'
+ ftl_status=Running
+ ftl_heatmap=''
+ ftl_check_box='[✓]'
++ ps -p 904 -o %cpu
++ tail -n1
++ tr -d '[:space:]'
+ ftl_cpu=0.3
++ ps -p 904 -o %mem
++ tail -n1
++ tr -d '[:space:]'
+ ftl_mem_percentage=0.1
++ GetFTLData dns-port
++ local ftl_port data
+++ getFTLAPIPort
+++ local FTLCONFFILE=/etc/pihole/pihole-FTL.conf
+++ local DEFAULT_FTL_PORT=4711
+++ local ftl_api_port
+++ '[' -s /etc/pihole/pihole-FTL.conf ']'
++++ grep '^FTLPORT=' /etc/pihole/pihole-FTL.conf
++++ cut -d= -f2-
++++ echo 4711
+++ ftl_api_port=4711
+++ expr 4711 : '[^[:digit:]]'
+++ echo 4711
++ ftl_port=4711
++ '[' -n 4711 ']'
+++ echo '>dns-port >quit'
+++ nc 127.0.0.1 4711
++ data=53
++ echo 53
+ ftl_dns_port=53
+ '[' 53 = 0 ']'
+ '[' Running = 'Not running' ']'
+ '[' enabled = enabled ']'
+ pihole_status=Active
+ pihole_heatmap=''
+ pihole_check_box='[✓]'
+ '[' enabled = disabled ']'
+ '[' enabled = unknown ']'
+ echo '- Gathering network information...'
- Gathering network information...
+ GetNetworkInformation regular
++ ip addr
++ grep 'inet '
++ grep -v 127.0.0.1/8
++ cut -f1 -d/
++ wc -l
++ awk '{print $2}'
+ pi_ip4_addrs=1
+ '[' 1 -eq 0 ']'
+ '[' 1 -eq 1 ']'
++ ip addr
++ grep 'inet '
++ grep -v 127.0.0.1/8
++ cut -f1 -d/
++ awk '{print $2}'
++ head -n 1
+ pi_ip4_addr=192.168.200.200
++ ip addr
++ grep 'inet6 '
++ grep -v ::1/128
++ cut -f1 -d/
++ wc -l
++ awk '{print $2}'
+ pi_ip6_addrs=0
+ '[' 0 -eq 0 ']'
+ pi_ip6_addr=N/A
+ ipv6_check_box='[✗]'
++ hostname
+ pi_hostname=raspberrypi
++ ip r
++ grep default
++ awk '{print $3}'
+ pi_gateway=192.168.200.1
+ full_hostname=raspberrypi
+ '[' -n '' ']'
+ dns_count=0
+ '[' -n 208.67.222.222 ']'
+ dns_count=1
+ '[' -n 208.67.220.220 ']'
+ dns_count=2
+ '[' -n 1.1.1.1 ']'
+ dns_count=3
+ '[' -n 1.0.0.1 ']'
+ dns_count=4
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' 4 -eq 1 ']'
+ '[' 4 -gt 8 ']'
+ dns_information='4 servers'
+ '[' '' = true ']'
+ dhcp_status=Disabled
+ dhcp_heatmap=''
+ dhcp_check_box='[✗]'
+ '[' -z ']'
++ GetFTLData gateway
++ local ftl_port data
++ awk '{ printf $1 }'
+++ getFTLAPIPort
+++ local FTLCONFFILE=/etc/pihole/pihole-FTL.conf
+++ local DEFAULT_FTL_PORT=4711
+++ local ftl_api_port
+++ '[' -s /etc/pihole/pihole-FTL.conf ']'
++++ grep '^FTLPORT=' /etc/pihole/pihole-FTL.conf
++++ cut -d= -f2-
++++ echo 4711
+++ ftl_api_port=4711
+++ expr 4711 : '[^[:digit:]]'
+++ echo 4711
++ ftl_port=4711
++ '[' -n 4711 ']'
+++ echo '>gateway >quit'
+++ nc 127.0.0.1 4711
++ data='192.168.200.1 eth0'
++ echo '192.168.200.1 eth0'
+ DHCP_ROUTER=192.168.200.1
+ dhcp_info=' Router:   192.168.200.1'
+ dhcp_heatmap=''
+ dhcp_check_box='[✗]'
+ dhcp_ipv6_status=N/A
+ dhcp_ipv6_heatmap=''
+ dhcp_ipv6_check_box='[?]'
+ '[' false = true ']'
+ dnssec_status=Disabled
+ dnssec_heatmap=''
+ '[' '' = true ']'
+ '[' false = true ']'
+ conditional_forwarding_status=Disabled
+ conditional_forwarding_heatmap=''
++ GetFTLData interfaces
++ head -n1
++ local ftl_port data
+++ getFTLAPIPort
+++ local FTLCONFFILE=/etc/pihole/pihole-FTL.conf
+++ local DEFAULT_FTL_PORT=4711
+++ local ftl_api_port
+++ '[' -s /etc/pihole/pihole-FTL.conf ']'
++++ grep '^FTLPORT=' /etc/pihole/pihole-FTL.conf
++++ cut -d= -f2-
++++ echo 4711
+++ ftl_api_port=4711
+++ expr 4711 : '[^[:digit:]]'
+++ echo 4711
++ ftl_port=4711
++ '[' -n 4711 ']'
+++ echo '>interfaces >quit'
+++ nc 127.0.0.1 4711
++ data='eth0 UP 1000 16.0MB 24.5MB 192.168.200.200 -
lo UP -1 87.0MB 87.0MB 127.0.0.1 -
sum UP 0 102.9MB 111.5MB - -'
++ echo 'eth0 UP 1000 16.0MB 24.5MB 192.168.200.200 -
lo UP -1 87.0MB 87.0MB 127.0.0.1 -
sum UP 0 102.9MB 111.5MB - -'
+ def_iface_data='eth0 UP 1000 16.0MB 24.5MB 192.168.200.200 -'
++ echo 'eth0 UP 1000 16.0MB 24.5MB 192.168.200.200 -'
++ awk '{print $1}'
+ iface_name=eth0
++ echo 'eth0 UP 1000 16.0MB 24.5MB 192.168.200.200 -'
++ awk '{print $4}'
+ tx_bytes=16.0MB
++ echo 'eth0 UP 1000 16.0MB 24.5MB 192.168.200.200 -'
++ awk '{print $5}'
+ rx_bytes=24.5MB
+ echo '- Gathering version information...'
- Gathering version information...
+ GetVersionInformation regular
++ echo v5.14.1
++ tr -d '[:alpha:]'
+ core_version=5.14.1
++ echo v5.14.1
++ tr -d '[:alpha:]'
+ core_version_latest=5.14.1
+ echo 5.14.1
+ grep -qE '^[0-9]+([.][0-9]+){1,2}$'
+ '[' 5.14.1 = ERROR ']'
+ '[' 5.14.1 '!=' 5.14.1 ']'
+ core_version_heatmap=''
+ core_version=v5.14.1
+ '[' true = true ']'
++ echo v5.17
++ tr -d '[:alpha:]'
+ web_version=5.17
++ echo v5.17
++ tr -d '[:alpha:]'
+ web_version_latest=5.17
+ echo 5.17
+ grep -qE '^[0-9]+([.][0-9]+){1,2}$'
+ '[' 5.17 = ERROR ']'
++ echo 5.17
++ tr -d '\r\n[:alpha:]'
+ web_version_latest=5.17
+ '[' 5.17 '!=' 5.17 ']'
+ web_version_heatmap=''
+ web_version=v5.17
++ echo v5.19.1
++ tr -d '[:alpha:]'
+ ftl_version=5.19.1
++ echo v5.19.1
++ tr -d '[:alpha:]'
+ ftl_version_latest=5.19.1
+ echo 5.19.1
+ grep -qE '^[0-9]+([.][0-9]+){1,2}$'
+ '[' 5.19.1 = ERROR ']'
+ '[' 5.19.1 '!=' 5.19.1 ']'
+ ftl_version_heatmap=''
+ ftl_version=v5.19.1
++ curl --silent https://api.github.com/repos/pi-hole/PADD/releases/latest
++ grep '"tag_name":'
++ awk -F '"' '{print $4}'
+ padd_version_latest=v3.8.1
+ '[' -z v3.8.1 ']'
++ VersionConverter v3.8.1
++ echo v3.8.1
++ tr -d '[:alpha:]'
++ awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'
+ padd_version_latest_converted=3008001000
++ VersionConverter v3.8.1
++ echo v3.8.1
++ tr -d '[:alpha:]'
++ awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'
+ padd_version_converted=3008001000
+ '[' 3008001000 -lt 3008001000 ']'
+ padd_version_heatmap=''
+ '[' '' = true ']'
+ '[' '' = true ']'
+ version_status='Pi-hole is up-to-date!'
+ pico_status='[✓] Sys. OK'
+ mini_status='[✓] System OK'
+ tiny_status='[✓] System is healthy.'
+ NormalPADD
+ true
+ PrintDashboard regular
+ '[' regular = pico ']'
+ '[' regular = nano ']'
+ '[' regular = micro ']'
+ '[' regular = mini ']'
+ '[' regular = tiny ']'
+ '[' regular = regular ']'
+ '[' regular = slim ']'
+ printf '%s\n' ' __      __  __   '
 __      __  __
+ printf '%s\n' '|__) /\ |  \|  \  Pi-hole® v5.14.1, Web v5.17, FTL v5.19.1'
|__) /\ |  \|  \  Pi-hole® v5.14.1, Web v5.17, FTL v5.19.1
+ printf '%s\n' '|   /--\|__/|__/  PADD v3.8.1   [✓] System is healthy.'
|   /--\|__/|__/  PADD v3.8.1   [✓] System is healthy.
+ printf '%s\n' ''

+ printf '%s\n' 'PI-HOLE ==================================================='
PI-HOLE ===================================================
+ printf ' %-10s%-19s %-10s%-19s\n' Status: Active FTL: Running
 Status:   Active              FTL:      Running
+ printf '%s\n' 'STATS ====================================================='
STATS =====================================================
+ printf ' %-10s%-49s\n' Blocking: '513484 domains'
 Blocking: 513484 domains
+ printf ' %-10s[%-40s] %-5s\n' Pi-holed: '■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
■■■' 1.5%
 Pi-holed: [■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■] 1.5%
+ printf ' %-10s%-49s\n' Pi-holed: '1295 out of 84477 queries'
 Pi-holed: 1295 out of 84477 queries
+ printf ' %-10s%-39s\n' Latest: app-measurement.com
 Latest:   app-measurement.com
+ printf ' %-10s%-39s\n' 'Top Ad:' events.launchdarkly.com
 Top Ad:   events.launchdarkly.com
+ '[' '' '!=' true ']'
+ printf ' %-10s%-39s\n' 'Top Dmn:' exceed-primary-production-lb.intellum.com
 Top Dmn:  exceed-primary-production-lb.intellum.com
+ printf ' %-10s%-39s\n' 'Top Clnt:' 192.168.200.171
 Top Clnt: 192.168.200.171
+ printf '%s\n' 'NETWORK ==================================================='
NETWORK ===================================================
+ printf ' %-10s%-15s %-4s%-17s%-6s%s\n' Hostname: raspberrypi IP: 192.168.200.2
00 IPv6: '[✗]'
 Hostname: raspberrypi     IP: 192.168.200.200  IPv6: [✗]
+ printf ' %-10s%-15s %-4s%-5s %-4s%-5s\n' Interfce: eth0 TX: 16.0MB RX: 24.5MB
 Interfce: eth0            TX: 16.0MB RX: 24.5MB
+ printf ' %-10s%-15s %-10s%-19s\n' DNS: '4 servers' DNSSEC: Disabled
 DNS:      4 servers       DNSSEC:   Disabled
+ '[' '' = true ']'
+ printf '%s\n' 'SYSTEM ===================================================='
SYSTEM ====================================================
+ printf ' %-10s%-39s\n' Uptime: '0 days, 21 hours, 25 minutes'
 Uptime:   0 days, 21 hours, 25 minutes
+ printf ' %-10s%-21s%-10s%-4s, %-4s, %-4s\n' 'CPU Temp:' $'40.4\302\260C' 'CPU
Load:' 1.08 0.84 0.82
 CPU Temp: 40.4°C              CPU Load: 1.08, 0.84, 0.82
+ printf ' %-10s[%-10s] %-6s %-10s[%-10s] %-5s' Memory: '··········' 2.2% 'CPU L
oad:' '■■■·······' 27.0%
 Memory:   [··········] 2.2%   CPU Load: [■■■·······] 27.0%+ tput ed
+ pico_status='[✓] Sys. OK'
+ mini_status='[✓] System OK'
+ tiny_status='[✓] System is healthy.'
+ full_status='[✓] System is healthy.'
+ mega_status='[✓] Your system is healthy.'
+ sleep 5
^C++ setterm -cursor on
++ echo

++ exit 0
+ setterm -cursor on
+ echo

+ exit 0
<redacted>@raspberrypi:~ $
```

**Comment by kagegoomba** [comment]
![image](https://user-images.githubusercontent.com/91712065/202306404-9a41fa4f-5ea1-4e9a-afe8-2c1e44710b8b.png)

**Comment by kagegoomba** [comment]
Well this is awkward - it just turned green just now.
Didn't touch it - didn't do nothing to it since last mod of the .sh file from your instruction.
o.o;

**Comment by yubiuser** [comment]
I'm glad it's solved now. I was a bit concerned already.

**Comment by kagegoomba** [comment]
Only concerning thing is why/what caused it. Guess I'll report back when/if next update occurs if it repeats.

**Comment by christianboyle** [comment]
Same issue here, but none of the above fixes have worked. I've tried the following:

I tried running `pihole updatechecker`, but it returns nothing and things are still red.

Also tried another `pihole up` and reboot this morning, but still no change.

Also tried replacing `padd.sh` with [https://raw.githubusercontent.com/pi-hole/PADD/versions_file/padd.sh](https://raw.githubusercontent.com/pi-hole/PADD/versions_file/padd.sh), but still nothing.

Anything else I might try?

**Comment by yubiuser** [comment]
@christianboyle 

Only the `Pi-hole` version is in red? Does it also show "out-of-date" when it's starting up?

**Comment by christianboyle** [comment]
@yubiuser Sorry, all 3 are red:

![IMG_2191](https://user-images.githubusercontent.com/1605754/202478674-fda70530-7673-4180-b455-fd8acf37d064.jpg)

**Comment by yubiuser** [comment]
I pushed an update to that branch. Please update your local version and try again. If it does not work, please provide the output of  `bash -x padd.sh`. The interesting lines look like

```
- Gathering version information...
+ GetVersionInformation mega
+ echo v5.14.1
+ grep -qE '^v[0-9]+([.][0-9]+){1,2}$'
++ VersionConverter v5.14.1
++ echo v5.14.1
++ tr -d '[:alpha:]'
++ awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'
+ core_version_converted=5014001000
++ VersionConverter v5.14.1
++ echo v5.14.1
++ tr -d '[:alpha:]'
++ awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'
+ core_version_latest_converted=5014001000
+ '[' 5014001000 -lt 5014001000 ']'
+ core_version_heatmap=''
+ '[' true = true ']'
+ echo v5.17-2-gf841f309
+ grep -qE '^v[0-9]+([.][0-9]+){1,2}$'
+ WEB_VERSION=N/A
+ web_version_heatmap=''
+ echo vDev-b72d3b7
+ grep -qE '^v[0-9]+([.][0-9]+){1,2}$'
+ FTL_VERSION=N/A
+ ftl_version_heatmap=''
++ curl --silent https://api.github.com/repos/pi-hole/PADD/releases/latest
++ grep '"tag_name":'
++ awk -F '"' '{print $4}'
+ padd_version_latest=v3.8.1
+ '[' -z v3.8.1 ']'
++ VersionConverter v3.8.1
++ echo v3.8.1
++ tr -d '[:alpha:]'
++ awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'
+ padd_version_latest_converted=3008001000
++ VersionConverter v3.8.1
++ echo v3.8.1
++ tr -d '[:alpha:]'
++ awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'
+ padd_version_converted=3008001000
+ '[' 3008001000 -lt 3008001000 ']'
+ padd_version_heatmap=''
+ '[' '' = true ']'
+ '[' '' = true ']'
+ version_status='Pi-hole is up-to-date!'

```

**Comment by christianboyle** [comment]
@yubiuser Your change fixed it, all 3 are green now.

**Comment by kagegoomba** [comment]
I'll do an update later tonight and see if anything happens - as I don't like a "modded" padd.sh off the main branch. :)

**Comment by yubiuser** [comment]
> padd.sh file from the main master branch just now 

> except the Pi-hole core - its red 

This is expected, as

> We made some last minute changes before the last release which affect the way the version information are displayed. PADD now fails to get the right information.

You need to use the special version provided at 
https://raw.githubusercontent.com/pi-hole/PADD/versions_file/padd.sh

to fix the issue. Or you wait until this fix has been released with a new PADD version.

**Comment by kagegoomba** [comment]
Ah - misread - ill try that again when I get a chance.

**Comment by kagegoomba** [comment]
came up totally green and normal with the modded file. It's happy again. :)

**Comment by kagegoomba** [comment]
FYI - update to pi-hole core today - current PADD File is working fine thusfar.

**Comment by yubiuser** [comment]
Should be fixed now with release of https://github.com/pi-hole/PADD/releases/tag/v3.9.0
