### ISSUE TITLE
Fit PADDmini propely into adafruit 320x240 2.8 TFT screen.

### ISSUE THREAD

**Issue by Profesyor** [pi-hole/PADD#86]
Hi, please fit PADDmini into  320x240 2.8 or resize the full version for the 2.8" screen.
![Padd Right](https://user-images.githubusercontent.com/59099536/75884667-a3881380-5dfb-11ea-82af-487eec3a7c72.jpg)

**Comment by Kerdic** [comment]
Not sure if this helps any, but I use the adafruit 320x240 screen, and ended up customizing the logic to better utilize the screen. (Note: my bezel blocks some of the first character, so this script shifts the section headers to the right one space also). And after this 3.1 update to stop flickering, I have noticed some artifacts (random characters at the end of the lines) I need to identify and clean up.

Anyway, here it is if it helps anyone. All modifications are marked in blocks of custom start and custom end. It would be nice if there was official support to better utilize that screen size however.

![piholr](https://user-images.githubusercontent.com/13769421/76460406-efaef700-63ab-11ea-8b04-199dd3528dd5.png)


[padd.txt](https://github.com/jpmck/PADD/files/4320681/padd.txt)

**Comment by Profesyor** [comment]
I have the same bezel, look at all that info THANK YOU!!!!!!!

**Comment by Kerdic** [comment]
No problem. I save a customized version out of the way, since updating PADD replaces the padd.sh file entirely. Which means, after every PADD update, I manually work in my custom changes to the new version, and attempt to update the custom with new enhancements.

**Comment by Profesyor** [comment]
Pfff. I'm getting ./padd.sh Permission denied

**Comment by Profesyor** [comment]
Fixed

**Comment by Profesyor** [comment]
Keep me posted. The random characters at the end of the lines, I got a 1> today. Couldn't this be due to the X amount of = in the NETWORK and the SYSTEM line?

**Comment by Kerdic** [comment]
Updated
[padd.txt](https://github.com/jpmck/PADD/files/4330027/padd.txt)


I implemented the relevant changes from these two pull requests into the custom section, I think that should fix the random characters and improve the version checking. Let me know if you still get them:
https://github.com/jpmck/PADD/pull/90
https://github.com/jpmck/PADD/pull/85

**Comment by Profesyor** [comment]
Fantastic works like a dream!

**Comment by carltonwb** [comment]
Pardon my newness but I saved the old padd.sh file to padd.sh.old, I then uploaded the padd.txt and changed the name to padd.sh.
Now what do I do. I did a sudo pihole -up and it said all was fine.
Still shows it saying update available.
Thanks

**Comment by Kerdic** [comment]
Yeah, the pihole -up downloads the latest padd.sh, so this customized/unofficial padd.sh that you put in place was replaced with the newest official padd.sh.

So, you should be able to repeat the steps, and instead of doing pihole -up, just restart to pick up the new script.

**Comment by carltonwb** [comment]
Thank you.
Did a reboot but did not work.
Did a shutdown and restart and that worked fine.
Appreciate it.

**Comment by kokein** [comment]
> Yeah, the pihole -up downloads the latest padd.sh, so this customized/unofficial padd.sh that you put in place was replaced with the newest official padd.sh.
> 
> So, you should be able to repeat the steps, and instead of doing pihole -up, just restart to pick up the new script.

Hi, this is great ! Can I buy You a coffe :) ? Do you have any support link ?

**Comment by mctehlers** [comment]
> Pardon my newness but I saved the old padd.sh file to padd.sh.old, I then uploaded the padd.txt and changed the name to padd.sh.
> Now what do I do. I did a sudo pihole -up and it said all was fine.
> Still shows it saying update available.
> Thanks

Did the same thing and a shutdown and reboot. But I'm just getting permission denied errors.. What should I do? Chmod xx?

**Comment by Profesyor** [comment]
> Updated
> [padd.txt](https://github.com/jpmck/PADD/files/4330027/padd.txt)
> 
> I implemented the relevant changes from these two pull requests into the custom section, I think that should fix the random characters and improve the version checking. Let me know if you still get them:
> #90
> #85

New Update

**Comment by Profesyor** [comment]
@Kerdic 
New Padd Update

**Comment by Profesyor** [comment]
https://github.com/jpmck/PADD/releases/tag/v3.2.1
Latest version

**Comment by Kerdic** [comment]
Here is the custom I have with 3.2.1.

One user mentioned they would prefer the memory bar to line up with the rest, so I made that change as well. However, the display is shifted one line at initial boot until the first update. Still looking into that... but here is what I have at the moment.

[padd.txt](https://github.com/jpmck/PADD/files/4887038/padd.txt)

**Comment by Profesyor** [comment]
@Kerdic Thanks, it works as always! I see the shifted line at the bottom but, meh you'll figure it out. He said this was his last update, I guess it's up to "us" now to keep it working like a charm, as always.

**Comment by KnownAim** [comment]
> @Kerdic Thanks, it works as always! I see the shifted line at the bottom but, meh you'll figure it out. He said this was his last update, I guess it's up to "us" now to keep it working like a charm, as always.

Well, the repository was moved into pi-hole's so it looks like the devs there are continuing maintenance. Looks like as of now, a lot of the bugs have been squashed, but there is always room for improvement, such as this.

**Comment by dschaper** [comment]
Heyup, we have moved PADD over to the Pi-hole namespace with the intention of keeping things going.

**Comment by Profesyor** [comment]
Aaaand it's broken now!

**Comment by dschaper** [comment]
PADD is fine, it's doing exactly what it should.

**Comment by Profesyor** [comment]
I've seen it. Pi-hole dashboard is broken after update 5.1

**Comment by dschaper** [comment]
I know, it's not PADD that is broken though.

**Comment by dschaper** [comment]
`echo 4711 | sudo tee /var/run/pihole-FTL.port` should work temporarily.

**Comment by Kerdic** [comment]
v3.2.2 for anyone interested
[padd.txt](https://github.com/pi-hole/PADD/files/4940379/padd.txt)

**Comment by dschaper** [comment]
Do you want to PR your changes to see if this will work in the main release?

**Comment by Profesyor** [comment]
@Kerdic, of course, we're interested!!!!

Thank you.

**Comment by Kerdic** [comment]
> Do you want to PR your changes to see if this will work in the main release?

I will try and look into that this weekend. I would think we should have a more official size name (I was just using PADDcust and custom), and I need to verify the screen size check logic that determines to use the "custom" size, to make sure it wouldn't have ill effects on other screen sizes that should remain using mini,

But yeah, it would be great to get support for this screen into production. I am open to any formatting changes as needed to make the output look cleaner. I know the FTL section isn't up to par (no ===== divider), but I wanted to get that information on the screen. :)

**Comment by Profesyor** [comment]
PADD2.8 
in color.

**Comment by Profesyor** [comment]
I'm still getting:
Blocking: 0 Domains
Piholed: [ _______________________ ] 0%
Piholed: 0 out of 0
Latest: 0
Top Ad:

**Comment by Kerdic** [comment]
Yeah, that is due to a bug in FTL from what I understand.

You will have to get to a command line and run the following below, then it should show the information correctly again. They said it should be fixed in a couple days.

echo 4711 | sudo tee /var/run/pihole-FTL.port

**Comment by dschaper** [comment]
"Tiny" is in the master branch. Version 3.3.

**Comment by Profesyor** [comment]
Pi-hole stopped working after these updates 3.3 no internet! I'm DONE with this! tried 3.3.1 same no internet.
Update pi-hole fails. Screen and all in the trash bin! I don't care anymore!

**Comment by dschaper** [comment]
PADD has nothing to do with Pi-hole's functions. 

But go ahead and toss the baby out the pram, it's only hurting you.

**Comment by Profesyor** [comment]
> PADD has nothing to do with Pi-hole's functions.
> 
> But go ahead and toss the baby out the pram, it's only hurting you.

Not blaming anyone. It was working ok before, I did nothing but update to 3.3 But I'm the reason this thread even exists. 

**Profesyor opened this issue on Mar 4**

**Comment by dschaper** [comment]
Again, there is absolutely nothing in PADD that can do anything to stop Pi-hole.

**Comment by dschaper** [comment]
> It should have been left alone after 3.2.2

That version doesn't have the tiny display. But feel free to install v3.2.2 and go back to what ever you think works.

**Comment by Profesyor** [comment]
So Pi-hole just stops working then?

**Comment by dschaper** [comment]
> So Pi-hole just stops working then?

Apparently so. I'm done with this discussion now.

**Comment by Profesyor** [comment]
> > So Pi-hole just stops working then?
> 
> Apparently so. I'm done with this discussion now.

And you're a JERK!!!!!!!

**Comment by mctehlers** [comment]
So pardon me, but what are the current steps to get this working?

**Comment by dschaper** [comment]
Install the latest release according to the README. Everything has been merged.
